<div class="title">Погода: <span><?=$city;?></span></div>
<div class="items">
    <div class="item night">
        <div class="text">ночь: <span><?=$nightData->tmin?>&#8451;</span></div>
         <img height="50" width="50" src="<?=$nightImgUrl?>" alt="">
    </div>
    <div class="item day">
        <div class="text">день: <span><?=$dayData->tmax?>&#8451;</span></div>
       <img height="50" width="50" src="<?=$dayImgUrl;?>" alt="">
    </div>
    <a href="http://goo.gl/IRwPRj"><img src="<?=plugin_dir_url(__FILE__).'img/meteoprog_logo.png'?>" /></a>
</div><!--items-->